// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYgkMSOuBMI7oOzPwKRND_8pVtCbyKz2E',
    appId: '1:927486469276:web:0bf155e68d328d985fb959',
    messagingSenderId: '927486469276',
    projectId: 'jurii-push',
    authDomain: 'jurii-push.firebaseapp.com',
    storageBucket: 'jurii-push.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaUEyf5pSCXEW9qK4zRnaZNt6pRc0wefU',
    appId: '1:927486469276:android:e1b904b9f01ad21f5fb959',
    messagingSenderId: '927486469276',
    projectId: 'jurii-push',
    storageBucket: 'jurii-push.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxZblMb3x4AZB1hcc9pEOW6dkZyep6pXs',
    appId: '1:927486469276:ios:0752821eb75003435fb959',
    messagingSenderId: '927486469276',
    projectId: 'jurii-push',
    storageBucket: 'jurii-push.firebasestorage.app',
    iosBundleId: 'br.com.jurii.app',
  );
}
